// Bilingual copy dictionary for the homepage (App.tsx).
//
// Keys are grouped by page section. `en` is the source of truth; `es` is typed
// as `typeof en` so the two key sets can never drift apart (a missing/extra key
// in `es` is a compile error). Reference copy at render sites via T[lang].<key>.
//
// DO NOT TRANSLATE, per brand/aviation rules: 'PreFlight 107', the tagline
// 'Plan it. Fly it. Prove it.', the feature name 'Fly Now Score', aviation
// acronyms (FAA, Part 107, LAANC, METAR, TAF, SIGMET, AIRMET, PIREP, NOTAM,
// ADS-B, TFR, VFR, BVLOS, NWS, NOAA, ASOS/AWOS), and proper nouns (App Store,
// Google Play, Apple Wallet, PassKit, AirMap, Aloft). 'AI' → 'IA' in Spanish.

const en = {
  // ── Nav ──
  nav_features: 'Features',
  nav_logs: 'Flight Logs',
  nav_pricing: 'Pricing',
  nav_compare: 'Compare',
  nav_flyable: 'Can I Fly?',
  nav_blog: 'Blog',
  nav_help: 'Help',
  nav_support: 'Support',
  nav_downloadFree: 'Download Free',
  nav_dashboard: 'Dashboard',
  nav_signOut: 'Sign Out',
  nav_logIn: 'Log In',
  nav_toggleAria: 'Toggle navigation',

  // ── Hero ──
  hero_badge: 'For Part 107 & Recreational Pilots',
  hero_title: 'Is it safe to fly today? Get your answer in one tap.',
  hero_subtitle: 'A free 0–100 go/no-go score for every flight — wind, gusts, airspace, and weather decoded into one number you can trust. Plus FAA-style Mission Briefings, live ADS-B traffic, and a verifiable pilot card for commercial work.',
  hero_subtitleRec: 'Free for recreational pilots — plus a 7-day free Pro+ trial for commercial work.',
  hero_ctaDownload: 'Download Free',
  hero_ctaTrial: 'Try Pro+ Free for 7 Days →',
  hero_joinBeta: 'Join iOS Beta',
  hero_androidSoonAria: 'Android version coming soon — join the waitlist',
  hero_comingSoon: 'Coming Soon',
  hero_onAndroid: 'on Android',
  hero_statBriefingsValue: 'FAA-Style',
  hero_statBriefingsLabel: 'Mission Briefings',
  hero_statAdsbValue: 'Live',
  hero_statAdsbLabel: 'ADS-B Traffic',
  hero_statCardValue: 'Verifiable',
  hero_statCardLabel: 'Pilot Card',

  // ── Mission Briefings section ──
  brf_eyebrow: 'New · Pro+',
  brf_helpAria: 'How Mission Briefings work',
  brf_helpLabel: 'How does this work?',
  brf_title: 'FAA-Style Mission Briefings',
  brf_lede: 'One tap generates a tamper-evident, multi-page Pre-Flight Briefing PDF — the same kind of document manned-aviation flight departments file. Live METAR/TAF, SIGMETs, AIRMETs, PIREPs, NOTAMs, sun & civil twilight times, LAANC status, and your full pilot/aircraft block.',
  brf_check1: 'Plain-English weather decode alongside the raw codes',
  brf_check2a: 'SHA-256 tamper hash + public',
  brf_check2b: 'page',
  brf_check3: 'White-label "Client Mode" — your logo, your branding',
  brf_check4: 'Recurring briefings on schedule (Pro+)',
  brf_check5: 'Public profile link clients can verify in any browser',
  brf_ctaPlans: 'See Pro+ Plans →',
  brf_ctaReadPost: 'Read the briefing post',
  brf_docEyebrow: 'PRE-FLIGHT MISSION BRIEFING',
  brf_docPilot: 'Pilot:',
  brf_docSite: 'Site:',
  brf_docWindow: 'Window:',
  brf_docWindowVal: '14:00–16:30 local',
  brf_docTafVal: 'VFR window',
  brf_docSigmetVal: 'None active',
  brf_docNotamVal: '2 reviewed',
  brf_docLaancVal: 'Auto-approve',
  brf_docVerify: 'verify at /verify',

  // ── Features ──
  feat_subtitle: 'Everything a commercial Part 107 operation needs, in one app.',
  feat_bucketPlan: 'Plan',
  feat_bucketPlanTitle: 'Pre-flight, briefings, and authorization',
  feat_bucketFly: 'Fly',
  feat_bucketFlyTitle: 'In-flight awareness and weather',
  feat_bucketProve: 'Prove',
  feat_bucketProveTitle: 'Records, credentials, and client deliverables',
  tag_free: 'Free',
  tag_pro: 'Pro',
  tag_proplus: 'Pro+',
  // Plan cards
  feat_briefingsTitle: 'Mission Briefings',
  feat_briefingsDesc: 'Tamper-evident PDF briefings with weather, hazards, NOTAMs, LAANC status, and pilot block — generated in seconds and verifiable by anyone.',
  feat_metarTitle: 'METAR / TAF / SIGMET',
  feat_metarDesc: 'Full aviation weather product suite with decoded plain-English versions alongside the raw codes — the same intel manned pilots use.',
  feat_recurringTitle: 'Recurring Briefings',
  feat_recurringDesc: 'Schedule a daily or weekly briefing for a recurring site (inspection routes, surveys, real-estate beats). Delivered automatically.',
  feat_laancTitle: 'LAANC Grid Overlays',
  feat_laancDesc: 'UAS facility map overlays show ceiling limits and authorization status before you ever open the LAANC portal.',
  // Fly cards
  feat_scoreTitle: 'Fly Now Score',
  feat_scoreDesc: 'One 0–100 go/no-go number that fuses wind, gusts, ceiling, visibility, hazards, and airspace into a single read — tap it for a plain-English breakdown of exactly why. Included free.',
  feat_densityTitle: 'Density Altitude',
  feat_densityDesc: 'Hot, high, and humid air is thinner — and thin air robs your drone of thrust, climb, and flight time. We compute it live for your exact spot and flag it before you fly. Included free.',
  feat_aiTitle: 'AI Risk Assessment',
  feat_aiDesc: 'Tap once for an AI go/no-go read on your exact conditions — plain-English reasoning plus recommended mitigations, in seconds. 3 free previews; unlimited with Pro+.',
  feat_radarTitle: 'Live ADS-B Radar',
  feat_radarDesc: 'Real-time manned aircraft tracking on your map with proximity warnings. Never share airspace unexpectedly — see every plane around you, live.',
  feat_windTitle: '3D Wind Tower',
  feat_windDesc: 'Visualize wind speed and direction at multiple altitudes in a 3D tower view. Know what the wind is doing at 50ft, 100ft, and 400ft before you climb.',
  feat_forecastTitle: '15-Day Forecast',
  feat_forecastDesc: "High-resolution atmospheric model data extended out two weeks. Plan job windows around the weather you'll actually have.",
  feat_airspaceTitle: 'Live Airspace Map',
  feat_airspaceDesc: 'Class B/C/D/E airspace, restricted zones, TFRs, and your current position — included free, forever.',
  // Prove cards
  feat_walletTitle: 'Apple Wallet Pilot Card',
  feat_walletDesc: 'A real PassKit card with your Part 107 number, account code, and a tap-to-verify link. Hand a client your phone and they see your credentials.',
  feat_profileTitle: 'Public Pilot Profile',
  feat_profileDescA: 'A shareable web profile at',
  feat_profileDescB: 'any client can open in any browser. Verified Part 107 badge, flight history, hour count.',
  feat_whitelabelTitle: 'White-Label Client Mode',
  feat_whitelabelDesc: 'Swap PreFlight 107 branding for your own business logo on briefing PDFs. Hand clients a polished deliverable that looks like your company.',
  feat_tamperTitle: 'Tamper-Evident PDFs',
  feat_tamperDescA: 'Every briefing carries a SHA-256 hash and a unique briefing code. Anyone can verify authenticity at',

  // ── Flight Logs ──
  logs_eyebrow: 'Cloud-Synced',
  logs_title: 'Your Flight Logbook, Always with You',
  logs_body: 'Tap "Log Flight" when you\'re done in the field and PreFlight 107 does the heavy lifting. Your GPS coordinates, drone model, live wind speed, temperature, and insurance details are all pre-filled automatically — you just add your flight time, mission notes, and you\'re done.',
  logs_check1: 'GPS coordinates auto-filled at log time',
  logs_check2: 'Live wind speed & temperature pulled from weather data',
  logs_check3: 'Active drone model pre-populated automatically',
  logs_check4: 'Insurance details synced from your pilot profile',
  logs_check5: 'Export any log as a shareable PDF report',
  logs_check6: '3 free logs — unlimited with Pro',
  logs_cardTitle: 'Flight Log #047',
  logs_cardDate: 'Mar 24, 2026 · 9:41 AM',
  logs_statDuration: 'Duration',
  logs_statTemp: 'Temp',
  logs_statWind: 'Wind',

  // ── Pricing ──
  pr_title: 'Choose Your Plan',
  pr_subtitle: "Start free. Upgrade when you're ready to fly further.",
  pr_monthly: 'Monthly',
  pr_annual: 'Annual',
  pr_save: 'Save 33%',
  pr_perMo: '/mo',
  pr_perYr: '/yr',
  pr_moEquivPro: '$6.67/mo',
  pr_moEquivProPlus: '$13.33/mo',
  pr_freeTier: 'Basic',
  pr_freePrice: 'Free',
  pr_freeDesc: 'Everything you need to get up in the air.',
  pr_free1: 'Live Airspace Map (Class B/C/D/E)',
  pr_free2: 'Live ADS-B Radar',
  pr_free3: 'Current Weather Dashboard',
  pr_free4: '24-hr Forecast',
  pr_free5: 'LAANC Status Lookup',
  pr_free6: "Cinematographer's Forecast",
  pr_free7: '3 Flight Logs',
  pr_freeBtn: 'Download Free',
  pr_popular: 'Most Popular',
  pr_proTier: 'Pro Pilot',
  pr_proDesc: 'For the working Part 107 pilot. Unlimited flying, full aviation weather, verified pilot card.',
  pr_pro1: 'Everything in Basic',
  pr_pro2: 'Live ADS-B Radar',
  pr_pro3: 'METAR / TAF / SIGMET',
  pr_pro4: '15-Day Forecast',
  pr_pro5: '3D Wind Tower',
  pr_pro6: 'Unlimited Flight Logs',
  pr_pro7: 'Flying Insights + Client Bundle',
  pr_pro8: 'Apple Wallet Pilot Card',
  pr_pro9: 'Public Pilot Profile',
  pr_proBtn: 'Get Pro Pilot →',
  pr_proplusBadge: 'For Commercial Ops',
  pr_proplusTier: 'Pro+ Operator',
  pr_proplusDesc: 'For pilots who deliver to clients. Mission Briefings, white-label PDFs, and recurring schedules.',
  pr_pp1: 'Everything in Pro Pilot',
  pr_pp2: 'FAA-Style Mission Briefings',
  pr_pp3: 'Tamper-Evident PDFs + /verify',
  pr_pp4: 'Plain-English Weather Decode',
  pr_pp5: 'White-Label Client Mode',
  pr_pp6: 'Recurring Briefings',
  pr_pp7: 'AI Morning Brief',
  pr_pp8: 'Live Observer Link',
  pr_pp9: 'Priority Support',
  pr_proplusBtn: 'Get Pro+ Operator →',
  pr_fineprint: 'Subscriptions are managed inside the app via your Apple ID — tap a plan to download, then pick your tier on the in-app paywall. Cancel anytime in Settings.',

  // ── Comparison table ──
  cmp_title: 'Full Feature Comparison',
  cmp_hFeature: 'Feature',
  cmp_hBasic: 'Basic',
  cmp_hPro: 'Pro Pilot',
  cmp_hProplus: 'Pro+ Operator',
  cmp_logs3: '3 logs',
  cmp_unlimited: 'Unlimited',
  cmp_airspace: 'Live Airspace Map',
  cmp_weather: 'Current Weather',
  cmp_forecast24: '24-hr Forecast',
  cmp_laancStatus: 'LAANC Status Lookup',
  cmp_adsb: 'Live ADS-B Radar',
  cmp_cine: "Cinematographer's Forecast",
  cmp_compliance: 'Compliance Reminders',
  cmp_logs: 'Flight Logs',
  cmp_metar: 'METAR / TAF / SIGMET',
  cmp_forecast15: '15-Day Forecast',
  cmp_wind: '3D Wind Tower',
  cmp_laancGrid: 'LAANC Grid Overlays',
  cmp_wallet: 'Apple Wallet Pilot Card',
  cmp_profile: 'Public Pilot Profile',
  cmp_pdfExport: 'PDF Log Exports',
  cmp_insights: 'Flying Insights',
  cmp_bundle: 'Client Bundle (per-job PDF)',
  cmp_briefings: 'Mission Briefings (PDF)',
  cmp_tamper: 'Tamper Hash + /verify',
  cmp_decode: 'Plain-English Decode',
  cmp_whitelabel: 'White-Label Client Mode',
  cmp_recurring: 'Recurring Briefings',
  cmp_morning: 'AI Morning Brief',
  cmp_observer: 'Live Observer Link',
  cmp_priority: 'Priority Support',

  // ── Android Early Access ──
  and_badge: 'Available Soon on',
  and_title: 'Android Early Access',
  and_sub: "Android support is actively in development. Drop your email and you'll be the first to know when we launch.",
  and_success: "You're on the list! We'll notify you as soon as the Android version takes flight.",
  and_emailPlaceholder: 'your@email.com',
  and_sending: 'Sending…',
  and_notify: 'Notify Me',
  and_error: 'Something went wrong — please try again.',

  // ── FAQ ──
  faq_title: 'Frequently Asked Questions',
  faq: [
    {
      q: 'Do I need an FAA Part 107 certificate to use this?',
      a: 'No certificate required to use the app. PreFlight 107 is free to download and use by anyone. An FAA Part 107 Remote Pilot Certificate is required only if you fly commercially — the app simply helps you fly smarter, whether you\'re recreational or certified.',
    },
    {
      q: 'Is the app free?',
      a: 'Yes. The core features — airspace map, basic weather, and LAANC status — are completely free. <strong>Pro Pilot</strong> ($9.99/month or $79.99/year) unlocks ADS-B live traffic radar, METAR/TAF briefings, 3D Wind Tower, the Apple Wallet pilot card, and unlimited flight logs. <strong>Pro+ Operator</strong> ($19.99/month or $159.99/year) adds FAA-style Mission Briefings, tamper-evident PDFs, white-label client mode, and recurring briefings.',
    },
    {
      q: 'What is a Mission Briefing?',
      a: 'A Mission Briefing is a multi-page, FAA-style pre-flight PDF generated by the app in seconds. It pulls live METAR/TAF, SIGMETs, AIRMETs, PIREPs, NOTAMs, sun & civil twilight times, and LAANC status for your site and combines it with your pilot/aircraft block. Every briefing carries a SHA-256 tamper hash and a unique briefing code, so anyone can verify it at <a href="/verify">preflight107.com/verify</a>. It\'s a Pro+ feature designed for commercial pilots who need to hand clients real documentation.',
    },
    {
      q: 'What is White-Label Client Mode?',
      a: 'Pro+ subscribers can upload a business logo and toggle "Client Mode" on any Mission Briefing. The output PDF swaps PreFlight 107 branding for yours, so the deliverable your client receives looks like it came from your company — not from an app. Great for inspection, real-estate, mapping, and survey operators who bill clients directly.',
    },
    {
      q: 'Can clients verify a briefing or pilot card I share?',
      a: 'Yes. Every Mission Briefing PDF includes a briefing code (like MB-XKA5RC) and a SHA-256 hash. Anyone can paste those into <a href="/verify">preflight107.com/verify</a> in a browser and confirm the briefing is authentic and unmodified. Your Apple Wallet pilot card and public profile (<code>preflight107.com/pilot/[code]</code>) are also verifiable — clients can open the link without installing anything.',
    },
    {
      q: 'What is LAANC?',
      a: "LAANC (Low Altitude Authorization and Notification Capability) is the FAA's automated system for granting near-real-time airspace authorization to drone pilots. Instead of waiting days for manual approval, LAANC lets you get cleared to fly in controlled airspace in seconds — directly inside PreFlight 107.",
    },
    {
      q: 'What is ADS-B?',
      a: 'ADS-B (Automatic Dependent Surveillance–Broadcast) is a technology that lets aircraft broadcast their position, altitude, speed, and tail number in real time. PreFlight 107 Pro pulls live ADS-B data so you can see manned aircraft sharing your airspace before you take off.',
    },
    {
      q: 'Does it work on Android?',
      a: 'PreFlight 107 is currently available on iOS (iPhone and iPad). Android support is actively in development — sign up in the section above to be the first to know when we launch.',
    },
    {
      q: 'How do I sign up?',
      a: 'Download PreFlight 107 free from the App Store, then create an account directly in the app. Pro upgrades are handled through your Apple ID — no separate billing account needed.',
    },
    {
      q: 'Can I use it offline?',
      a: 'The base map tiles are cached for offline viewing. Live features — ADS-B radar, real-time weather, and LAANC authorization — require an active internet connection.',
    },
    {
      q: 'Where does your weather data come from?',
      a: 'PreFlight 107 pulls aviation weather directly from the National Weather Service (NWS) and NOAA data feeds — the same sources used by professional aviation weather services. METARs and TAFs are sourced from official ASOS/AWOS stations, and the 15-day extended forecast uses high-resolution atmospheric model data.',
    },
    {
      q: 'Where does ADS-B data come from?',
      a: 'Live ADS-B data is sourced from a network of ground-based receivers that collect aircraft transponder broadcasts in real time. The data is aggregated from FAA and community ADS-B networks, giving you comprehensive manned traffic awareness across most of the United States.',
    },
    {
      q: 'Is my flight data private?',
      a: 'Yes. Your flight logs are stored securely in your account and are never shared with third parties, the FAA, or anyone else. You control your data — logs are only visible to you unless you choose to export or share them. See our Privacy Policy for full details.',
    },
    {
      q: 'Do flight logs help with FAA record-keeping?',
      a: 'Yes. Part 107 commercial pilots are expected to maintain records of their operations. PreFlight 107\'s cloud-synced flight logs let you record location, date, duration, drone details, and notes in one place — making it straightforward to stay organized and retrieve records when needed.',
    },
    {
      q: 'How is this different from AirMap or Aloft?',
      a: 'PreFlight 107 is built around the full preflight intelligence workflow: real aviation weather (METAR, TAF, PIREPs), live ADS-B traffic, 3D wind analysis, and cloud-synced flight logs — all in one place. Where other tools focus primarily on airspace authorization, PreFlight 107 layers in the weather and situational awareness data that professional pilots actually depend on before and during every flight.',
    },
    {
      q: 'Can I share flight logs with clients?',
      a: 'Pro subscribers can export flight logs as professional PDF reports — including weather conditions at flight time, drone details, flight duration, and location. These are ideal for sharing with clients as proof of flight, for insurance documentation, or for project records.',
    },
    {
      q: 'Can I access my data on the web?',
      a: "Yes — PreFlight 107 has a web dashboard you can access right from this site. Create an account or log in and you'll be able to view your saved flight logs, drone info, and account details from any browser, synced with what's in the app.",
    },
  ],

  // ── Footer ──
  ft_tagline: 'Fly safe out there.',
  ft_ariaX: 'Follow PreFlight 107 on X',
  ft_ariaFb: 'Follow PreFlight 107 on Facebook',
  ft_ariaReddit: 'Join the PreFlight 107 community on Reddit',
  ft_ariaIg: 'Follow PreFlight 107 on Instagram',
  ft_privacy: 'Privacy Policy',
  ft_terms: 'Terms of Service',
  ft_support: 'Support',
  ft_delete: 'Delete Account',
  ft_blog: 'Blog',
  ft_help: 'Help',
  ft_flyable: 'Can I Fly?',
  ft_copy: '© 2026 PreFlight 107. All rights reserved.',

  // ── Briefing Help modal ──
  bh_title: 'How Mission Briefings work',
  bh_subtitle: 'The plan side of your paper trail',
  bh_close: 'Close',
  bh_s1Title: 'What is a Mission Briefing?',
  bh_s1Body: "It's the document you create BEFORE you fly — your written plan. It proves to a client, the FAA, or an insurance adjuster that you did your homework: weather forecast, airspace check, NOTAMs, risk assessment, crew, emergency contacts, landowner permission, the works.",
  bh_s2Title: 'Who needs one?',
  bh_s2a: 'Commercial Part 107 pilots taking paid jobs',
  bh_s2b: 'Complex missions (BVLOS, multi-aircraft, dense airspace)',
  bh_s2c: 'Recurring inspections — pair with the briefing scheduler',
  bh_s2d: "Casual hobby flights at the local park don't need one.",
  bh_s3Title: 'When do I create one?',
  bh_s3Body: "Any time before takeoff — minutes ahead, days ahead, weeks ahead. The form asks WHEN you plan to fly, and the weather section pulls the FORECAST for that exact time (NWS gridded data covers ~10 days out). If you're flying tomorrow at 9am, you get tomorrow's 9am forecast — not today's METAR.",
  bh_s4Title: 'How the workflow goes',
  bh_s4step1: "<strong>PLAN</strong> — Create a Mission Briefing. You get a code (MB-XXXXXX), a tamper-verified 6-page PDF, and a row in 'My Briefings.'",
  bh_s4step2: '<strong>FLY</strong> — On the Dashboard, tap Start Flight. The app asks "Link this flight to MB-XXXXXX?" — tap Yes.',
  bh_s4step3: '<strong>DOCUMENT</strong> — After landing, your flight log card shows three buttons: Flight Log, FAA Evidence, and Mission Brief. The Evidence PDF footer references your briefing code, tying the plan to what actually happened.',
  bh_s5Title: 'Why briefings are locked once generated',
  bh_s5Body1: "Every generated briefing carries a SHA-256 tamper hash. That hash is what makes it admissible as evidence — change one character and the hash mismatches. So we don't let you edit a briefing after generation.",
  bh_s5Body2: 'If forecast was wrong on flight day, don\'t edit — tap "Update" on the briefing card. We clone it, you tweak weather + risks, and you get a fresh briefing (e.g. MB-8L4K2M — updated from MB-7K3F9P). Both stay in your list, so your paper trail shows you reassessed when conditions changed. That\'s STRONGER legally, not weaker.',
  bh_s6Title: 'Mission Briefing vs. FAA Evidence',
  bh_s6Body: 'Two different documents, both per-flight, both important:',
  bh_s6ColAh: 'Mission Briefing <em>(the PLAN)</em>',
  bh_s6ColA1: 'Forecast weather, planned crew, intended mitigations',
  bh_s6ColA2: 'Pre-flight, locked, anti-falsification',
  bh_s6ColA3: 'Shows due diligence',
  bh_s6ColBh: 'FAA Evidence Packet <em>(the RECORD)</em>',
  bh_s6ColB1: 'Realtime METAR, server-stamped GPS + timestamps',
  bh_s6ColB2: 'Captured at Depart, locked at Land',
  bh_s6ColB3: 'Shows what was actually true at takeoff',
  bh_s6Footer: 'Together they tell the complete story.',
  bh_s7Title: 'Briefing Defaults (Settings)',
  bh_s7Body: 'Tired of re-typing your business contact, default crew, and emergency contacts every time? Set them once in Settings → Briefing Defaults and they pre-fill every new briefing. You can still override per-mission.',
  bh_cta: 'Got it',

  // ── Beta modal ──
  beta_ariaLabel: 'Join the Beta',
  beta_success: "You're on the list! We'll be in touch when beta access opens.",
  beta_earlyAccess: 'Early Access',
  beta_iosBeta: 'iOS Beta',
  beta_title: 'Join the iOS Beta',
  beta_sub: "Get early access to PreFlight 107 on iOS before public launch. Drop your info and we'll reach out when a spot opens up.",
  beta_namePlaceholder: 'Your name',
  beta_emailPlaceholder: 'your@email.com',
  beta_sending: 'Sending…',
  beta_request: 'Request Beta Access',
  beta_error: 'Something went wrong — please try again.',
};

const es: typeof en = {
  // ── Nav ──
  nav_features: 'Funciones',
  nav_logs: 'Bitácoras',
  nav_pricing: 'Precios',
  nav_compare: 'Comparar',
  nav_flyable: '¿Puedo volar?',
  nav_blog: 'Blog',
  nav_help: 'Ayuda',
  nav_support: 'Soporte',
  nav_downloadFree: 'Descarga gratis',
  nav_dashboard: 'Panel',
  nav_signOut: 'Cerrar sesión',
  nav_logIn: 'Iniciar sesión',
  nav_toggleAria: 'Alternar navegación',

  // ── Hero ──
  hero_badge: 'Para pilotos Part 107 y recreativos',
  hero_title: '¿Es seguro volar hoy? Ten tu respuesta con un toque.',
  hero_subtitle: 'Una puntuación gratuita de 0 a 100 de vuela/no vueles para cada vuelo: viento, ráfagas, espacio aéreo y clima traducidos en un solo número confiable. Además, Informes de Misión estilo FAA, tráfico ADS-B en vivo y una credencial de piloto verificable para trabajos comerciales.',
  hero_subtitleRec: 'Gratis para pilotos recreativos, con una prueba gratis de Pro+ de 7 días para trabajos comerciales.',
  hero_ctaDownload: 'Descarga gratis',
  hero_ctaTrial: 'Prueba Pro+ gratis 7 días →',
  hero_joinBeta: 'Unirse a la beta de iOS',
  hero_androidSoonAria: 'Versión Android muy pronto: únete a la lista de espera',
  hero_comingSoon: 'Muy pronto',
  hero_onAndroid: 'en Android',
  hero_statBriefingsValue: 'Estilo FAA',
  hero_statBriefingsLabel: 'Informes de Misión',
  hero_statAdsbValue: 'En vivo',
  hero_statAdsbLabel: 'Tráfico ADS-B',
  hero_statCardValue: 'Verificable',
  hero_statCardLabel: 'Credencial de piloto',

  // ── Mission Briefings section ──
  brf_eyebrow: 'Nuevo · Pro+',
  brf_helpAria: 'Cómo funcionan los Informes de Misión',
  brf_helpLabel: '¿Cómo funciona esto?',
  brf_title: 'Informes de Misión estilo FAA',
  brf_lede: 'Con un toque generas un PDF de varias páginas de informe previo al vuelo a prueba de manipulaciones, el mismo tipo de documento que archivan los departamentos de vuelo de la aviación tripulada. METAR/TAF en vivo, SIGMET, AIRMET, PIREP, NOTAM, horas de sol y crepúsculo civil, estado LAANC y tu bloque completo de piloto/aeronave.',
  brf_check1: 'Decodificación del clima en lenguaje claro junto a los códigos originales',
  brf_check2a: 'Hash de manipulación SHA-256 + página pública',
  brf_check2b: '',
  brf_check3: 'Modo Cliente de marca blanca: tu logo, tu marca',
  brf_check4: 'Informes recurrentes programados (Pro+)',
  brf_check5: 'Enlace de perfil público que los clientes pueden verificar en cualquier navegador',
  brf_ctaPlans: 'Ver planes Pro+ →',
  brf_ctaReadPost: 'Leer el artículo sobre informes',
  brf_docEyebrow: 'INFORME DE MISIÓN PREVIO AL VUELO',
  brf_docPilot: 'Piloto:',
  brf_docSite: 'Sitio:',
  brf_docWindow: 'Ventana:',
  brf_docWindowVal: '14:00–16:30 local',
  brf_docTafVal: 'Ventana VFR',
  brf_docSigmetVal: 'Ninguno activo',
  brf_docNotamVal: '2 revisados',
  brf_docLaancVal: 'Aprob. automática',
  brf_docVerify: 'verifica en /verify',

  // ── Features ──
  feat_subtitle: 'Todo lo que una operación comercial Part 107 necesita, en una sola app.',
  feat_bucketPlan: 'Planifica',
  feat_bucketPlanTitle: 'Previo al vuelo, informes y autorización',
  feat_bucketFly: 'Vuela',
  feat_bucketFlyTitle: 'Conciencia en vuelo y clima',
  feat_bucketProve: 'Demuestra',
  feat_bucketProveTitle: 'Registros, credenciales y entregables para clientes',
  tag_free: 'Gratis',
  tag_pro: 'Pro',
  tag_proplus: 'Pro+',
  // Plan cards
  feat_briefingsTitle: 'Informes de Misión',
  feat_briefingsDesc: 'Informes en PDF a prueba de manipulaciones con clima, peligros, NOTAM, estado LAANC y bloque de piloto, generados en segundos y verificables por cualquiera.',
  feat_metarTitle: 'METAR / TAF / SIGMET',
  feat_metarDesc: 'Suite completa de productos meteorológicos de aviación con versiones decodificadas en lenguaje claro junto a los códigos originales: la misma información que usan los pilotos tripulados.',
  feat_recurringTitle: 'Informes Recurrentes',
  feat_recurringDesc: 'Programa un informe diario o semanal para un sitio recurrente (rutas de inspección, levantamientos, recorridos inmobiliarios). Se entrega automáticamente.',
  feat_laancTitle: 'Capas de Cuadrícula LAANC',
  feat_laancDesc: 'Las capas del mapa de instalaciones UAS muestran los límites de techo y el estado de autorización antes de abrir el portal LAANC.',
  // Fly cards
  feat_scoreTitle: 'Fly Now Score',
  feat_scoreDesc: 'Un único número de 0 a 100 de vuela/no vueles que combina viento, ráfagas, techo, visibilidad, peligros y espacio aéreo en una sola lectura; tócalo para ver en lenguaje claro exactamente por qué. Incluido gratis.',
  feat_densityTitle: 'Altitud de Densidad',
  feat_densityDesc: 'El aire caliente, en altura y húmedo es más ligero, y el aire ligero le resta empuje, ascenso y tiempo de vuelo a tu dron. Lo calculamos en vivo para tu ubicación exacta y te avisamos antes de volar. Incluido gratis.',
  feat_aiTitle: 'Evaluación de Riesgo con IA',
  feat_aiDesc: 'Toca una vez para una lectura de vuela/no vueles con IA sobre tus condiciones exactas: razonamiento en lenguaje claro y mitigaciones recomendadas, en segundos. 3 vistas previas gratis; ilimitadas con Pro+.',
  feat_radarTitle: 'Radar ADS-B en Vivo',
  feat_radarDesc: 'Seguimiento en tiempo real de aeronaves tripuladas en tu mapa con alertas de proximidad. Nunca compartas el espacio aéreo por sorpresa: ve cada avión a tu alrededor, en vivo.',
  feat_windTitle: 'Torre de Viento 3D',
  feat_windDesc: 'Visualiza la velocidad y dirección del viento a varias altitudes en una vista de torre 3D. Sabe qué hace el viento a 50, 100 y 400 ft antes de ascender.',
  feat_forecastTitle: 'Pronóstico de 15 Días',
  feat_forecastDesc: 'Datos de modelos atmosféricos de alta resolución extendidos a dos semanas. Planifica tus ventanas de trabajo según el clima que realmente tendrás.',
  feat_airspaceTitle: 'Mapa de Espacio Aéreo en Vivo',
  feat_airspaceDesc: 'Espacio aéreo Clase B/C/D/E, zonas restringidas, TFR y tu posición actual: incluido gratis, para siempre.',
  // Prove cards
  feat_walletTitle: 'Credencial de Piloto en Apple Wallet',
  feat_walletDesc: 'Una tarjeta PassKit real con tu número Part 107, código de cuenta y un enlace de verificación con un toque. Pásale el teléfono a un cliente y verá tus credenciales.',
  feat_profileTitle: 'Perfil Público de Piloto',
  feat_profileDescA: 'Un perfil web para compartir en',
  feat_profileDescB: 'que cualquier cliente puede abrir en cualquier navegador. Insignia Part 107 verificada, historial de vuelos y conteo de horas.',
  feat_whitelabelTitle: 'Modo Cliente de Marca Blanca',
  feat_whitelabelDesc: 'Cambia la marca de PreFlight 107 por el logo de tu propio negocio en los PDF de informes. Entrega a tus clientes un producto pulido que parece de tu empresa.',
  feat_tamperTitle: 'PDF a Prueba de Manipulaciones',
  feat_tamperDescA: 'Cada informe lleva un hash SHA-256 y un código de informe único. Cualquiera puede verificar la autenticidad en',

  // ── Flight Logs ──
  logs_eyebrow: 'Sincronizado en la nube',
  logs_title: 'Tu bitácora de vuelo, siempre contigo',
  logs_body: 'Toca "Registrar vuelo" al terminar en el campo y PreFlight 107 hace el trabajo pesado. Tus coordenadas GPS, modelo de dron, velocidad del viento en vivo, temperatura y datos del seguro se rellenan automáticamente; solo agregas tu tiempo de vuelo, las notas de la misión y listo.',
  logs_check1: 'Coordenadas GPS rellenadas automáticamente al registrar',
  logs_check2: 'Velocidad del viento y temperatura en vivo tomadas de los datos del clima',
  logs_check3: 'Modelo de dron activo precargado automáticamente',
  logs_check4: 'Datos del seguro sincronizados desde tu perfil de piloto',
  logs_check5: 'Exporta cualquier bitácora como un informe PDF para compartir',
  logs_check6: '3 bitácoras gratis; ilimitadas con Pro',
  logs_cardTitle: 'Bitácora de vuelo n.º 047',
  logs_cardDate: '24 mar 2026 · 9:41 a. m.',
  logs_statDuration: 'Duración',
  logs_statTemp: 'Temp',
  logs_statWind: 'Viento',

  // ── Pricing ──
  pr_title: 'Elige tu plan',
  pr_subtitle: 'Empieza gratis. Mejora cuando estés listo para llegar más lejos.',
  pr_monthly: 'Mensual',
  pr_annual: 'Anual',
  pr_save: 'Ahorra 33%',
  pr_perMo: '/mes',
  pr_perYr: '/año',
  pr_moEquivPro: '$6.67/mes',
  pr_moEquivProPlus: '$13.33/mes',
  pr_freeTier: 'Básico',
  pr_freePrice: 'Gratis',
  pr_freeDesc: 'Todo lo que necesitas para despegar.',
  pr_free1: 'Mapa de espacio aéreo en vivo (Clase B/C/D/E)',
  pr_free2: 'Radar ADS-B en vivo',
  pr_free3: 'Panel del clima actual',
  pr_free4: 'Pronóstico de 24 h',
  pr_free5: 'Consulta de estado LAANC',
  pr_free6: 'Pronóstico para cinematógrafos',
  pr_free7: '3 bitácoras de vuelo',
  pr_freeBtn: 'Descarga gratis',
  pr_popular: 'Más popular',
  pr_proTier: 'Piloto Pro',
  pr_proDesc: 'Para el piloto Part 107 en activo. Vuelo ilimitado, clima de aviación completo y credencial de piloto verificada.',
  pr_pro1: 'Todo lo de Básico',
  pr_pro2: 'Radar ADS-B en vivo',
  pr_pro3: 'METAR / TAF / SIGMET',
  pr_pro4: 'Pronóstico de 15 días',
  pr_pro5: 'Torre de viento 3D',
  pr_pro6: 'Bitácoras de vuelo ilimitadas',
  pr_pro7: 'Estadísticas de vuelo + Paquete para cliente',
  pr_pro8: 'Credencial de piloto en Apple Wallet',
  pr_pro9: 'Perfil público de piloto',
  pr_proBtn: 'Obtener Piloto Pro →',
  pr_proplusBadge: 'Para operaciones comerciales',
  pr_proplusTier: 'Operador Pro+',
  pr_proplusDesc: 'Para pilotos que entregan a clientes. Informes de Misión, PDF de marca blanca y programaciones recurrentes.',
  pr_pp1: 'Todo lo de Piloto Pro',
  pr_pp2: 'Informes de Misión estilo FAA',
  pr_pp3: 'PDF a prueba de manipulaciones + /verify',
  pr_pp4: 'Decodificación del clima en lenguaje claro',
  pr_pp5: 'Modo Cliente de marca blanca',
  pr_pp6: 'Informes recurrentes',
  pr_pp7: 'Informe matutino con IA',
  pr_pp8: 'Enlace de Observador en Vivo',
  pr_pp9: 'Soporte prioritario',
  pr_proplusBtn: 'Obtener Operador Pro+ →',
  pr_fineprint: 'Las suscripciones se gestionan dentro de la app con tu Apple ID: toca un plan para descargar y luego elige tu nivel en el paywall de la app. Cancela cuando quieras en Ajustes.',

  // ── Comparison table ──
  cmp_title: 'Comparación completa de funciones',
  cmp_hFeature: 'Función',
  cmp_hBasic: 'Básico',
  cmp_hPro: 'Piloto Pro',
  cmp_hProplus: 'Operador Pro+',
  cmp_logs3: '3 bitácoras',
  cmp_unlimited: 'Ilimitadas',
  cmp_airspace: 'Mapa de espacio aéreo en vivo',
  cmp_weather: 'Clima actual',
  cmp_forecast24: 'Pronóstico de 24 h',
  cmp_laancStatus: 'Consulta de estado LAANC',
  cmp_adsb: 'Radar ADS-B en vivo',
  cmp_cine: 'Pronóstico para cinematógrafos',
  cmp_compliance: 'Recordatorios de cumplimiento',
  cmp_logs: 'Bitácoras de vuelo',
  cmp_metar: 'METAR / TAF / SIGMET',
  cmp_forecast15: 'Pronóstico de 15 días',
  cmp_wind: 'Torre de viento 3D',
  cmp_laancGrid: 'Capas de cuadrícula LAANC',
  cmp_wallet: 'Credencial de piloto en Apple Wallet',
  cmp_profile: 'Perfil público de piloto',
  cmp_pdfExport: 'Exportación de bitácoras en PDF',
  cmp_insights: 'Estadísticas de vuelo',
  cmp_bundle: 'Paquete para cliente (PDF por trabajo)',
  cmp_briefings: 'Informes de Misión (PDF)',
  cmp_tamper: 'Hash de manipulación + /verify',
  cmp_decode: 'Decodificación en lenguaje claro',
  cmp_whitelabel: 'Modo Cliente de marca blanca',
  cmp_recurring: 'Informes recurrentes',
  cmp_morning: 'Informe matutino con IA',
  cmp_observer: 'Enlace de Observador en Vivo',
  cmp_priority: 'Soporte prioritario',

  // ── Android Early Access ──
  and_badge: 'Disponible muy pronto en',
  and_title: 'Acceso anticipado a Android',
  and_sub: 'El soporte para Android está en desarrollo activo. Déjanos tu correo y serás el primero en enterarte cuando lancemos.',
  and_success: '¡Estás en la lista! Te avisaremos en cuanto la versión de Android despegue.',
  and_emailPlaceholder: 'tu@correo.com',
  and_sending: 'Enviando…',
  and_notify: 'Avísame',
  and_error: 'Algo salió mal. Inténtalo de nuevo.',

  // ── FAQ ──
  faq_title: 'Preguntas frecuentes',
  faq: [
    {
      q: '¿Necesito un certificado FAA Part 107 para usar esto?',
      a: 'No se requiere certificado para usar la app. PreFlight 107 es gratis de descargar y usar para cualquiera. Un Certificado de Piloto Remoto FAA Part 107 solo es obligatorio si vuelas comercialmente; la app simplemente te ayuda a volar de forma más inteligente, seas recreativo o certificado.',
    },
    {
      q: '¿La app es gratis?',
      a: 'Sí. Las funciones principales (mapa de espacio aéreo, clima básico y estado LAANC) son completamente gratis. <strong>Piloto Pro</strong> ($9.99/mes o $79.99/año) desbloquea el radar de tráfico ADS-B en vivo, informes METAR/TAF, la Torre de viento 3D, la credencial de piloto en Apple Wallet y bitácoras de vuelo ilimitadas. <strong>Operador Pro+</strong> ($19.99/mes o $159.99/año) añade Informes de Misión estilo FAA, PDF a prueba de manipulaciones, modo cliente de marca blanca e informes recurrentes.',
    },
    {
      q: '¿Qué es un Informe de Misión?',
      a: 'Un Informe de Misión es un PDF previo al vuelo de varias páginas, estilo FAA, que la app genera en segundos. Reúne METAR/TAF en vivo, SIGMET, AIRMET, PIREP, NOTAM, horas de sol y crepúsculo civil y estado LAANC de tu sitio, y lo combina con tu bloque de piloto/aeronave. Cada informe lleva un hash de manipulación SHA-256 y un código de informe único, para que cualquiera pueda verificarlo en <a href="/es/verify">preflight107.com/verify</a>. Es una función Pro+ diseñada para pilotos comerciales que necesitan entregar documentación real a sus clientes.',
    },
    {
      q: '¿Qué es el Modo Cliente de marca blanca?',
      a: 'Los suscriptores de Pro+ pueden subir el logo de su negocio y activar el "Modo Cliente" en cualquier Informe de Misión. El PDF resultante cambia la marca de PreFlight 107 por la tuya, de modo que el entregable que recibe tu cliente parece venir de tu empresa y no de una app. Ideal para operadores de inspección, inmobiliaria, mapeo y levantamientos que facturan directamente a sus clientes.',
    },
    {
      q: '¿Los clientes pueden verificar un informe o una credencial de piloto que comparto?',
      a: 'Sí. Cada PDF de Informe de Misión incluye un código de informe (como MB-XKA5RC) y un hash SHA-256. Cualquiera puede pegarlos en <a href="/es/verify">preflight107.com/verify</a> en un navegador y confirmar que el informe es auténtico y no fue modificado. Tu credencial de piloto en Apple Wallet y tu perfil público (<code>preflight107.com/pilot/[code]</code>) también son verificables: los clientes pueden abrir el enlace sin instalar nada.',
    },
    {
      q: '¿Qué es LAANC?',
      a: 'LAANC (Low Altitude Authorization and Notification Capability) es el sistema automatizado de la FAA para otorgar autorización de espacio aéreo casi en tiempo real a los pilotos de drones. En lugar de esperar días por una aprobación manual, LAANC te permite obtener autorización para volar en espacio aéreo controlado en segundos, directamente dentro de PreFlight 107.',
    },
    {
      q: '¿Qué es ADS-B?',
      a: 'ADS-B (Automatic Dependent Surveillance–Broadcast) es una tecnología que permite a las aeronaves transmitir su posición, altitud, velocidad y matrícula en tiempo real. PreFlight 107 Pro obtiene datos ADS-B en vivo para que puedas ver las aeronaves tripuladas que comparten tu espacio aéreo antes de despegar.',
    },
    {
      q: '¿Funciona en Android?',
      a: 'PreFlight 107 está disponible actualmente en iOS (iPhone y iPad). El soporte para Android está en desarrollo activo; regístrate en la sección de arriba para ser el primero en enterarte cuando lancemos.',
    },
    {
      q: '¿Cómo me registro?',
      a: 'Descarga PreFlight 107 gratis desde la App Store y luego crea una cuenta directamente en la app. Las mejoras a Pro se gestionan a través de tu Apple ID: no necesitas una cuenta de facturación aparte.',
    },
    {
      q: '¿Puedo usarla sin conexión?',
      a: 'Las capas base del mapa se guardan en caché para verlas sin conexión. Las funciones en vivo (radar ADS-B, clima en tiempo real y autorización LAANC) requieren una conexión a internet activa.',
    },
    {
      q: '¿De dónde provienen tus datos del clima?',
      a: 'PreFlight 107 obtiene el clima de aviación directamente de los datos del National Weather Service (NWS) y NOAA, las mismas fuentes que usan los servicios profesionales de clima de aviación. Los METAR y TAF provienen de estaciones oficiales ASOS/AWOS, y el pronóstico extendido de 15 días usa datos de modelos atmosféricos de alta resolución.',
    },
    {
      q: '¿De dónde provienen los datos ADS-B?',
      a: 'Los datos ADS-B en vivo provienen de una red de receptores terrestres que recogen las transmisiones de los transpondedores de las aeronaves en tiempo real. Los datos se agregan de redes ADS-B de la FAA y de la comunidad, brindándote una conciencia completa del tráfico tripulado en la mayor parte de Estados Unidos.',
    },
    {
      q: '¿Mis datos de vuelo son privados?',
      a: 'Sí. Tus bitácoras de vuelo se almacenan de forma segura en tu cuenta y nunca se comparten con terceros, la FAA ni nadie más. Tú controlas tus datos: las bitácoras solo son visibles para ti a menos que decidas exportarlas o compartirlas. Consulta nuestra Política de Privacidad para más detalles.',
    },
    {
      q: '¿Las bitácoras de vuelo ayudan con el registro ante la FAA?',
      a: 'Sí. Se espera que los pilotos comerciales Part 107 mantengan registros de sus operaciones. Las bitácoras sincronizadas en la nube de PreFlight 107 te permiten registrar ubicación, fecha, duración, detalles del dron y notas en un solo lugar, facilitando mantenerte organizado y recuperar registros cuando los necesites.',
    },
    {
      q: '¿En qué se diferencia de AirMap o Aloft?',
      a: 'PreFlight 107 se construye en torno al flujo completo de inteligencia previa al vuelo: clima de aviación real (METAR, TAF, PIREP), tráfico ADS-B en vivo, análisis de viento 3D y bitácoras sincronizadas en la nube, todo en un solo lugar. Mientras otras herramientas se centran principalmente en la autorización de espacio aéreo, PreFlight 107 suma los datos de clima y conciencia situacional de los que los pilotos profesionales realmente dependen antes y durante cada vuelo.',
    },
    {
      q: '¿Puedo compartir bitácoras de vuelo con clientes?',
      a: 'Los suscriptores de Pro pueden exportar las bitácoras de vuelo como informes PDF profesionales, con las condiciones del clima al momento del vuelo, detalles del dron, duración del vuelo y ubicación. Son ideales para compartir con clientes como prueba de vuelo, para documentación de seguros o para registros de proyecto.',
    },
    {
      q: '¿Puedo acceder a mis datos en la web?',
      a: 'Sí. PreFlight 107 tiene un panel web al que puedes acceder desde este mismo sitio. Crea una cuenta o inicia sesión y podrás ver tus bitácoras de vuelo guardadas, la información de tu dron y los detalles de tu cuenta desde cualquier navegador, sincronizados con lo que está en la app.',
    },
  ],

  // ── Footer ──
  ft_tagline: 'Vuela seguro.',
  ft_ariaX: 'Sigue a PreFlight 107 en X',
  ft_ariaFb: 'Sigue a PreFlight 107 en Facebook',
  ft_ariaReddit: 'Únete a la comunidad de PreFlight 107 en Reddit',
  ft_ariaIg: 'Sigue a PreFlight 107 en Instagram',
  ft_privacy: 'Política de Privacidad',
  ft_terms: 'Términos del Servicio',
  ft_support: 'Soporte',
  ft_delete: 'Eliminar cuenta',
  ft_blog: 'Blog',
  ft_help: 'Ayuda',
  ft_flyable: '¿Puedo volar?',
  ft_copy: '© 2026 PreFlight 107. Todos los derechos reservados.',

  // ── Briefing Help modal ──
  bh_title: 'Cómo funcionan los Informes de Misión',
  bh_subtitle: 'El lado de la planificación de tu registro documental',
  bh_close: 'Cerrar',
  bh_s1Title: '¿Qué es un Informe de Misión?',
  bh_s1Body: 'Es el documento que creas ANTES de volar: tu plan por escrito. Le demuestra a un cliente, a la FAA o a un ajustador de seguros que hiciste la tarea: pronóstico del clima, revisión del espacio aéreo, NOTAM, evaluación de riesgo, tripulación, contactos de emergencia, permiso del propietario del terreno, todo.',
  bh_s2Title: '¿Quién necesita uno?',
  bh_s2a: 'Pilotos comerciales Part 107 que aceptan trabajos pagados',
  bh_s2b: 'Misiones complejas (BVLOS, varias aeronaves, espacio aéreo denso)',
  bh_s2c: 'Inspecciones recurrentes: combínalas con el programador de informes',
  bh_s2d: 'Los vuelos recreativos casuales en el parque local no necesitan uno.',
  bh_s3Title: '¿Cuándo creo uno?',
  bh_s3Body: 'En cualquier momento antes del despegue: minutos, días o semanas antes. El formulario pregunta CUÁNDO planeas volar, y la sección del clima trae el PRONÓSTICO para ese momento exacto (los datos en cuadrícula del NWS cubren ~10 días). Si vuelas mañana a las 9 a. m., obtienes el pronóstico de mañana a las 9 a. m., no el METAR de hoy.',
  bh_s4Title: 'Cómo es el flujo de trabajo',
  bh_s4step1: "<strong>PLANIFICA</strong> — Crea un Informe de Misión. Obtienes un código (MB-XXXXXX), un PDF de 6 páginas verificado contra manipulaciones y una fila en 'Mis Informes'.",
  bh_s4step2: '<strong>VUELA</strong> — En el Panel, toca Iniciar vuelo. La app pregunta "¿Vincular este vuelo a MB-XXXXXX?" — toca Sí.',
  bh_s4step3: '<strong>DOCUMENTA</strong> — Tras aterrizar, la tarjeta de tu bitácora muestra tres botones: Bitácora de vuelo, Evidencia FAA e Informe de Misión. El pie del PDF de Evidencia hace referencia a tu código de informe, uniendo el plan con lo que realmente ocurrió.',
  bh_s5Title: 'Por qué los informes se bloquean una vez generados',
  bh_s5Body1: 'Cada informe generado lleva un hash de manipulación SHA-256. Ese hash es lo que lo hace admisible como evidencia: cambia un solo carácter y el hash deja de coincidir. Por eso no permitimos editar un informe después de generarlo.',
  bh_s5Body2: 'Si el pronóstico falló el día del vuelo, no lo edites: toca "Actualizar" en la tarjeta del informe. Lo clonamos, tú ajustas el clima y los riesgos, y obtienes un informe nuevo (p. ej. MB-8L4K2M, actualizado desde MB-7K3F9P). Ambos permanecen en tu lista, así tu registro documental muestra que reevaluaste cuando las condiciones cambiaron. Eso es MÁS fuerte legalmente, no más débil.',
  bh_s6Title: 'Informe de Misión vs. Evidencia FAA',
  bh_s6Body: 'Dos documentos distintos, ambos por vuelo, ambos importantes:',
  bh_s6ColAh: 'Informe de Misión <em>(el PLAN)</em>',
  bh_s6ColA1: 'Clima pronosticado, tripulación planeada, mitigaciones previstas',
  bh_s6ColA2: 'Previo al vuelo, bloqueado, antifalsificación',
  bh_s6ColA3: 'Muestra debida diligencia',
  bh_s6ColBh: 'Paquete de Evidencia FAA <em>(el REGISTRO)</em>',
  bh_s6ColB1: 'METAR en tiempo real, GPS y marcas de tiempo selladas por el servidor',
  bh_s6ColB2: 'Capturado al Despegar, bloqueado al Aterrizar',
  bh_s6ColB3: 'Muestra lo que realmente era cierto al despegar',
  bh_s6Footer: 'Juntos cuentan la historia completa.',
  bh_s7Title: 'Valores predeterminados de informes (Ajustes)',
  bh_s7Body: '¿Cansado de reescribir tu contacto de negocio, la tripulación predeterminada y los contactos de emergencia cada vez? Configúralos una vez en Ajustes → Valores predeterminados de informes y se rellenarán en cada informe nuevo. Aun así puedes cambiarlos por misión.',
  bh_cta: 'Entendido',

  // ── Beta modal ──
  beta_ariaLabel: 'Únete a la beta',
  beta_success: '¡Estás en la lista! Te contactaremos cuando se abra el acceso a la beta.',
  beta_earlyAccess: 'Acceso anticipado',
  beta_iosBeta: 'Beta de iOS',
  beta_title: 'Únete a la beta de iOS',
  beta_sub: 'Obtén acceso anticipado a PreFlight 107 en iOS antes del lanzamiento público. Déjanos tus datos y te contactaremos cuando se abra un lugar.',
  beta_namePlaceholder: 'Tu nombre',
  beta_emailPlaceholder: 'tu@correo.com',
  beta_sending: 'Enviando…',
  beta_request: 'Solicitar acceso a la beta',
  beta_error: 'Algo salió mal. Inténtalo de nuevo.',
};

export const T = { en, es };
